#This script is used to clean the trash files, which are generated by copy or untar. 
#If you find reading and writing into some folders are very slow, you can use it to clean.
#sys.argv[0] is tot or bkg or sig
#sys.argv[1] is gg2e2m or gg4m or gg4e
#sys.argv[2] is jobs folder name
#!!!!del or mg must be in the sys.argv!!!! 
import sys
import os

if 'mg' in sys.argv:
    mypub="/publicfs/cms/user/mingxuanzhang/gridpack/simulation_tool/mg5condor/gg4l_{0}/{1}/{2}".format(sys.argv[1], sys.argv[2], sys.argv[3]) #this path is in ihep cluster
elif 'del' in sys.argv:
    mypub="/publicfs/cms/user/mingxuanzhang/gridpack/simulation_tool/delpycondor/gg4l_{0}/{1}/{2}".format(sys.argv[1], sys.argv[2], sys.argv[3]) #this path is in ihep cluster
else:
    print("\n !!!!del or mg must be in the sys.argv!!!! \n")

file_list = []
for i in range(100):
    file_list.append("{0}/{1}_{2}-0000{3:02d}".format(mypub, sys.argv[2], sys.argv[1], i))

for f in file_list:
    sub_files = os.listdir(f)
    #print(sub_files)
    for sub_file in sub_files:
        if sub_file == "cmsgrid_final.lhe" or sub_file == "showersimul.root":
            continue
        else:
            os.system("rm -rf {0}/{1}".format(f, sub_file))
